In [1]:
def nameFile(stri):
    char_count = 0
    year = ""
    counter = -1

    for character in stri:
        counter += 1

        if  counter+3 == len(stri):
            break
        if stri[counter].isdigit() and stri[counter+1].isdigit() and stri[counter+2].isdigit() and stri[counter+3].isdigit():
            year = stri[counter]+stri[counter+1]+stri[counter+2]+stri[counter+3]
        if len(year) == 4:
            return "Nytårstalen "+year

    return "Nytårstalen (årstal mangler)"

print(nameFile("2477"))

Nytårstalen 2477

In [2]:
#pip install nltk (just once)
import nltk #natural language toolkit
import re #regular expressions
import string #stringfunctions

In [3]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/jovyan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [4]:
#nltk.corpus.stopwords.words('danish')
sw_dk = nltk.corpus.stopwords.words('danish')

In [5]:
#sw_dk.append("testAtron")
#sw_dk

In [10]:
def open_speech(file):
    with open(file) as file_object:
        content = file_object.read()

    return content

#speech = open_speech("test_data/speech.txt")

In [9]:
def clean_speech(txt):
    txt = txt.lower() #sætter alle karaktere til lower case
    txt = re.sub('\n','', txt) #fjerner alle \n 
    txt = re.sub('\[.*?]','',txt) #fjerner [] og indholdet
    txt = re.sub('\([^)]*\)','',txt) #fjerner () og indholdet
    txt = re.sub('\d', '', txt) #fjerner tal(digits)
    txt = re.sub('[%s]' % re.escape(string.punctuation), '', txt) #fjerner tegn

    return txt

#speech = clean_speech(speech)

In [8]:
import datetime
def get_years():
    now = datetime.datetime.now()
    result = []
    year = 2001
    
    while year < now.year:
        
        result.append(year)
        year += 1
    
    return result
print(get_years())

[2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]

In [12]:
def create_data(years):
    data = {}
    file = ""
    
    for i, year in enumerate(years):
        file = 'test_data/Nytårstalen '+str(year)
        data[str(year)] = clean_speech(open_speech(file))
        
    return data

data_dict = create_data(get_years())
#data_dict

In [14]:
#Ændrer dict value fra string til list
def value_to_list(value):
    value_list = ''.join(value)
    
    return value_list

data_combined = {key: [value_to_list(value)] for (key, value) in data_dict.items()}
#data_combined

In [15]:
import pandas as pd
def data_dict_to_df(dict_data):
    df_data = pd.DataFrame.from_dict(data_combined).transpose()
    df_data.columns = ['speech']
    
    return df_data
#data_dict skal muligvis være data_combined
df_data = data_dict_to_df(data_dict)
df_data

                                                 speech
2001  årene går og i tilbageblikket får hvert af dem...
2002  det er nytårsaften  igen så alt for hurtigt sy...
2003  igen står et nyt år for døren et skudår oven i...
2004  ingen véd hvad et år kan bringe det har vi net...
2005  det er nytårsaften år  synger på sit allersids...
2006  ved et årsskifte er det almindeligt at se både...
2007  nytårsaften er et af årets mærkeligste højdepu...
2008  det er årets sidste aften efter julen med dens...
2009  nytårsaften er den aften hvor vi ser tilbage p...
2010  nytårsaften er det skik at se tilbage på året ...
2011  året har  dage det er ens for os alle men hvor...
2012  det er nytårsaften om få timer falder rådhuskl...
2013  helligdagene omkring jul og nytår er for de fl...
2014  nu er det nytårsaften bag os ligger et helt år...
2015  et år er ved at rinde ud i morgen står et nyt ...
2016  nu er der kun få timer tilbage af det gamle år...
2017  så er det nytårsaften – igendet er som om at d...
2018  så blev det igen nytårsaftennår klokken ved mi...
2019  så er endnu et år gået nu ligger  bag os med a...
2020  i aften står vi igen ved et årsskifte vi ser f...

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

cv_dk = CountVectorizer(stop_words=sw_dk) 
data_cv = cv_dk.fit_transform(df_data.speech)
data_dtm = pd.DataFrame(data_cv.toarray(), columns=cv_dk.get_feature_names())
data_dtm.index = df_data.index
data_dtm

,aarhus,absalon,accept,adskillige,affaldet,affinde,affødt,afghanistan,afgjort,afgrundemed,...,ønskerogså,ønsket,ønskeuddannelse,øre,ører,øresund,østersøregionenjeg,øverst,øvrige,øvrigt
2001,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
2002,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2003,0,0,0,0,0,0,1,0,0,0,...,0,1,0,1,0,0,0,0,1,0
2004,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
2005,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2006,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2007,0,0,0,0,0,0,0,2,0,0,...,0,1,0,0,0,0,0,0,0,0
2008,0,1,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
2009,0,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
2010,0,0,0,1,0,0,0,2,0,0,...,0,0,0,0,1,0,0,0,0,0
2011,0,0,0,0,0,0,0,1,0,0,...,1,0,1,0,0,0,0,0,0,0
2012,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2013,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,1
2014,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2015,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2016,5,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
2017,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
2018,0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2019,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2020,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
def top_words_all(amount):
    top_dict = {}
    data = data_dtm.transpose()
    for year in data.columns:
        top = data[year].sort_values(ascending=False).head(amount)
        top_dict[year] = list(zip(top.index, top.values))

    return top_dict

top_words_all(5)

{'2001': [('år', 14), ('kan', 13), ('danmark', 9), ('så', 9), ('må', 8)],
 '2002': [('år', 12), ('kan', 11), ('så', 8), ('danmark', 7), ('nye', 7)],
 '2003': [('kan', 11), ('så', 10), ('godt', 6), ('år', 6), ('tid', 5)],
 '2004': [('kan', 20), ('år', 11), ('må', 9), ('ved', 9), ('så', 8)],
 '2005': [('kan', 10), ('år', 10), ('danske', 10), ('danmark', 7), ('ved', 6)],
 '2006': [('år', 16), ('må', 11), ('danmark', 10), ('nye', 9), ('land', 8)],
 '2007': [('år', 16), ('må', 11), ('kan', 11), ('samfund', 7), ('godt', 6)],
 '2008': [('år', 13), ('kan', 12), ('vores', 9), ('godt', 8), ('nye', 7)],
 '2009': [('år', 14), ('så', 9), ('godt', 8), ('nye', 8), ('kan', 8)],
 '2010': [('kan', 16), ('år', 10), ('vore', 10), ('mindre', 8), ('så', 7)],
 '2011': [('kan', 24), ('år', 12), ('ved', 9), ('finde', 9), ('så', 9)],
 '2012': [('kan', 9), ('danmark', 8), ('vort', 8), ('sammen', 7), ('må', 7)],
 '2013': [('kan', 8), ('år', 8), ('danske', 7), ('ved', 6), ('godt', 6)],
 '2014': [('år', 15), ('kan', 14), ('så', 13), ('godt', 12), ('danmark', 9)],
 '2015': [('kan', 16), ('godt', 12), ('så', 11), ('år', 11), ('må', 9)],
 '2016': [('kan', 13),
  ('danske', 12),
  ('vores', 10),
  ('år', 10),
  ('kommer', 8)],
 '2017': [('kan', 12), ('så', 9), ('går', 8), ('år', 8), ('andre', 7)],
 '2018': [('kan', 16), ('så', 13), ('år', 12), ('godt', 10), ('ved', 8)],
 '2019': [('år', 16), ('kan', 8), ('danmark', 8), ('ved', 7), ('så', 6)],
 '2020': [('år', 15), ('godt', 8), ('måttet', 8), ('aften', 6), ('danske', 6)]}

In [18]:
def top_words_by_year(search_year, amount):
    top_dict = {}
    data = data_dtm.transpose()
    for x in data.columns:
        if search_year == int(x):
            top = data[x].sort_values(ascending=False).head(amount)
            top_dict[x] = list(zip(top.index, top.values))
            break

    return top_dict

    return top_dict
print(top_words_by_year(2005,10))

{'2005': [('kan', 10), ('år', 10), ('danske', 10), ('danmark', 7), ('ved', 6), ('nye', 6), ('bog', 6), ('så', 6), ('samfund', 6), ('andre', 6)]}